### ISSUE TITLE
Stopped working recently

### ISSUE THREAD

**Issue by markwilkinson** [linkeddata/tabulator#7]
It was working perfectly for me before, but now fails to render anything (I see quite a few 404's in the network trace in Developers tools)

Tried:  

Two pages - one that was working a couple of weeks ago, the other a new one.  This one should work:  http://biordf.org/cgi-bin/RD_Connect/EHDN_Accessor

Tried returning both rdf-xml and turtle.  neither worked.

Tried both Chrome in Windows and Chrome in Ubuntu Linux.  Neither worked.

I miss it :-(

**Comment by timbl** [comment]
Sorry the chrome extension is not supported at the moment, only the Firefox one.
